### ISSUE TITLE
How to obtain the floor position?

### ISSUE THREAD

**Issue by Xianjin111** [soshishimada/PhysCap_demo_release#12]
Thank you for your perfect work.

I use the openpose to obtain the 2D keypoints. I have a question about how to obtain the floor position?  Do I need to use VNect to obtain the floor position?

Thank you very much.

**Comment by soshishimada** [comment]
Hello, if you are recording your own sequences, you can place a checkerboard on the floor, and use it as a world frame when calibrating cameras, i.e., the world frame is where the floor is. For estimating floor positions in a youtube video, you can for example 1) run off the shelf 3D pose estimator (e.g. VNect http://vcai.mpi-inf.mpg.de/projects/VNect/), 2) obtain trajectories of foot 3D positions through a sequence 3) apply plain fitting onto the trajectory. This can give you a rough estimate of a floor position.

**Comment by Xianjin111** [comment]
Thank you very much.
